### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by SwissalpS**
- luacheck
- mod.conf
- recycling recipes
- fix formspec invsize -> size and add listring for shift-clicking between inventories
- replace outdated meta handling
- replace minetest -> core
- reduce indentation with smarter 'early exit' code
- fix pairs() -> ipairs() loop
- reduce chat spam when trying to dig a machine with items in it: not needed this is a general game mechanic
- update locales, drop intllib and add Spanish and Catalan
- restructure crafts to own file
- general cleanup with more informative comments

### CODE REVIEW

**Review by wsor4035 — APPROVED** [review]
makes sense

**Comment by SwissalpS** [comment]
do we have a problem with the WTF licence in this org? If so we might as well re-licence this.

**Comment by BuckarooBanzay** [comment]
> do we have a problem with the WTF licence in this org? If so we might as well re-licence this.

don't care IMO :shrug:

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by S-S-X** [comment]
> do we have a problem with the WTF licence in this org? If so we might as well re-licence this.

Just CDB had issues with certain licenses like WTFPL and that's why there's been talk about dual licensing on some repos, not sure how it is currently.

**Pull request merged**
