### PR TITLE
add mandarin stickers

### PR DESCRIPTION
**Pull request by SwissalpS**
I'm aware that this is just a mirror repo. The upstream repo does not offer method of submitting PR so I'm posting here for them to pull from. If somebody could notify maintainer, that would be great.

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
I think the owner of the repo if "OchNoe/OchNö" from linux-forks 
@Montandalar @yw05 (sorry for the ping) is there a way to contact them? LF doesn't have any social bridges...

**Comment by y5nw** [comment]
I am only aware of the advtrains mailing lists and `~gpcf/misc-patches@lists.sr.ht` for other patches. For Och_Noe you could try to send him (the email address can be found in the commit log) the patch but (considering my experience of talking with him about git) I am not sure how far that would go.

**Comment by S-S-X** [comment]
Even if there would be some way to send patches it is in my opinion bad idea if there's no simple tools for it, better to just fork it and setup job to grab updates from upstream.

Could notify upstream devs about fork later / when getting in touch

So then if they want they can easily get patches / diffs like this:
https://github.com/mt-mods/technic/pull/257.patch
https://github.com/mt-mods/technic/pull/257.diff
Or just merge stuff by adding github as another remote and pulling stuff from there.

Also even just sending patches by providing github urls or copy pasting to email is way simpler: allows us to have usable platform for discussion and workflow job integrations.

**Comment by y5nw** [comment]
> Even if there would be some way to send patches it is in my opinion bad idea if there's no simple tools for it, better to just fork it and setup job to grab updates from upstream.

There is `git send-email` for sending patches via email. Whether it is simple is subjective, though.

> So then if they want they can easily get patches / diffs like this: https://github.com/mt-mods/technic/pull/257.patch https://github.com/mt-mods/technic/pull/257.diff Or just merge stuff by adding github as another remote and pulling stuff from there.

I suppose the main reason sending patches with `git-send-email` is preferred is that some email clients allow you to pipe the email directly to `git am`. I did it a few times with advtrains.

**Comment by S-S-X** [comment]
> git send-email

That works only for few people, not for most users who do contribute to minetest mods. You should know that and I guess you also know reason for it...

> I suppose the main reason sending patches with git-send-email is preferred is that some email clients allow you to pipe the email directly to git am. I did it a few times with advtrains.

See above.

Besides that, you can just pipe `curl <github-patch-url> | git am` or `curl <github-diff-url> | git apply`, it also provides way to paste contents to mail in case user is not able to do that in command line (and most users are not able to).
Basically: using GitHub as platform allows everything you can do without GitHub but offers a lot of useful and easy to use features.

Patch urls also works for most basic things like commit ranges etc. https://github.com/mt-mods/technic/compare/99b0c46...ecea17.patch

Still not saying that using patch url has to be a way to merge stuff, it is just easy to use option that can be used if:
* User does not have cli or gui git client that is able to handle mails (many windows users)
* User does not have outgoing mail configured for git (many windows and linux users)
* User can write Lua code but only knows basic git stuff: commit, push and possibly some branch management
* User just happens to be writing code and committing directly from web browser using github editor, workflow is different from regular workflow (sometimes I do that)
* User wants to discuss options before doing changes or wants discussion / opinions with other users (because github provides easy to use user interface it is possible to reach a lot more users, discussion is really public)
* Some contributors wants to use fancy web UI and some wants to use direct email for discussions, works fairly well.
* And GitHub can even send patches to selected email addresses when pull request is merged to release/main branch from feature branch 📬

**Comment by y5nw** [comment]
> > git send-email
> 
> That works only for few people, not for most users who do contribute to minetest mods. You should know that and I guess you also know reason for it...

There are currently a few reasons I can think of against the use of git-send-email:
* Anonymity. Register another account or use an email alias (I know a few email providers that make it easy to do the latter)
* `git-send-email` does not work well with a proxy (this was reported by someone else): copy the content into the web interface.

> > I suppose the main reason sending patches with git-send-email is preferred is that some email clients allow you to pipe the email directly to git am. I did it a few times with advtrains.
> 
> See above.

In case I have not made this obvious enough: what I mentioned was the main reason of sending patches directly instead of the URL.

In reply to the "above" post, I do not see how email does _not_ "[allows people] to have usable platform for discussion". In case you do not have an idea of how email-based discussions on patches look like, here is an example: https://lists.sr.ht/~gpcf/advtrains/%3C20211226212113.21978-1-tanavit%40laposte.net%3E

The problem with CI (if that is what you mean by "workflow job integrations") is that nobody has set up CI for the mod. There are enough ways to do CI out there, and you can obviously do it with email-based discussions, as in the case with advtrains (I keep bringing this up because I have experience with it).

> Besides that, you can just pipe `curl <github-patch-url> | git am` or `curl <github-diff-url> | git apply`, it also provides way to paste contents to mail in case user is not able to do that in command line (and most users are not able to).

I am not sure why most users are not able to use the command line. This is not North Korea. Even Windows allows you to use Git in the CLI, and we do in fact have patches sent via email from Windows, in case you are wondering: https://lists.sr.ht/~gpcf/advtrains/patches/21549

Mass discussion is not Github-specific either. The fact that there is no mailing list for the ehlphabet mod does not mean you can't do mass mailing via email.

I am not sure how the rest of the "easy to use" arguments make sense (I started writing this post when the arguments were added, so I am not copying those over). In fact, I would say that one of the _advantages_ for advtrains to have email-based discussions over fancy UIs is that we keep out people who are not even competent enough to do 10 minutes of reading.

**Comment by S-S-X** [comment]
> In case you do not have an idea of how email-based discussions

What I am saying is that not all people want to use email based discussion, GitHub as a platform provides both email based and web UI based discussions and allows users to choose what they want and/or are able to use.

> I am not sure why most users are not able to use the command line.

Many windows users use various GUI clients and not all those provide easy way to use all core features but limited set of features that are still more than enough for contributions.

> Even Windows allows you to use Git in the CLI

Allows to use is completely different thing from know how and be able to. Windows allows you to run a lot of Linux programs through WSL, that's not the point.

> Mass discussion is not Github-specific either.

That's true and I think I already mentioned that GitHub allows both email based and web UI (with extremely easy access) based discussions.

> have email-based discussions over fancy UIs is that we keep out people who are not even competent enough to do 10 minutes of reading.

You know you can reply to this comment directly using your email and everyone subscribed discussing this pull request will get your reply? Thing is one of contributors can use fancy web UI while another can use email however they choose.

Personally I would be fine with CLI + email only workflow but not everyone is, thing with using GitHub (or some other similar git service) as a platform is that it gives more options for users.
You could simply go take a look at Minetest mods at ContentDB and see how many of those are hosted on GitHub / GitLab / similar platforms and then think about why users did choose to use those.

Take a look at https://content.minetest.net/packages/?random=1&lucky=1 say 10 times and take a look at source code link, where it is hosted? Then think about how many contributors are familiar with email + git workflow vs web ui (+possibly git) workflow.

**Comment by y5nw** [comment]
> You know you can reply to this comment directly using your email and everyone subscribed discussing this pull request will get your reply? Thing is one of contributors can use fancy web UI while another can use email however they choose.

Some mailing lists do have reply buttons if that is what you are after. There are web interfaces that register themselves as mailto: link handlers, so it is not necessary to set up an email client (that does depend on the provider, though). Also you can likely set up an email client in less than 15 minutes (including reading the tutorial) or so so it should not be a paritular problem.

> You could simply go take a look at Minetest mods at ContentDB and see how many of those are hosted on GitHub / GitLab / similar platforms and then think about why users did choose to use those.
> 
> Take a look at https://content.minetest.net/packages/?random=1&lucky=1 say 10 times and take a look at source code link, where it is hosted? Then think about how many contributors are familiar with email + git workflow vs web ui (+possibly git) workflow.

More importantly, how many people are aware of email-based platforms? Self hosting is not an option for most people out there, and Sourcehut is just a small platform that is still in testing phase. It should not be surprising that most people are not even _aware_ of git+email-based workflow/hosting platform, so being familiar with it or actively using it should be out of the question. Low awareness does not imply inferiority though, for obvious reasons (and as history has proven)

**Comment by Montandalar** [comment]
Och_Nö has an interesting relationship with git, as in he much prefers SVN and only commits direct to master and pushes to his stuff on Bananach Space. If you really need to get people to work inside the Pull Request/GitHub system, the best way I can probably think of to submit stuff to Och_Nö is for patches that get consensus here, make a script to email them to [~gpcf/misc-patches@lists.sr.ht]() as yw05 mentioned, a la git-send-email and hope gpcf and Och_Nö sort it out. Don't know if that can be done with GitHub actions? Yes, I know this is incredibly cumbersome to work with but I don't see it changing because the git email workflow is just how it's done for LinuxForks projects.

It might be work talking to gpcf to get more mailing lists set up on Sourcehut since it's currently only advtrains and misc-patches, but I also don't know how the licensing works and if that would cost gpcf more. gpcf should respond promptly to email if you wanted to talk to him about it. That way for any minetest-mirrors repos, the script to send the git emails can just point at an appropriate and specific mailing list. At some point you need to get your hands dirty with the mailing list anyway because I'm sure the maintainer would prefer to respond on the mailing list.

My reasoning having been explained I will summarise my suggested approach:

1. Opening a PR on a minetest-mirrors that points to git.bananach.space should automagically send an email to the appropriate mailing list (for now misc-patches, in future specific) on sourcehut.
2. PR submitter needs to respond to any queries from the maintainer via email*. They probably don't need to subscribe to the mailing list as long as the thread doesn't get broken.
3. Once maintainer responds over on sourcehut: whether it gets rejected or accepted, you have to close the PR and not merge it. The maintainer will merge using the git email workflow which will create different commit hashes.
4. The script that fetches from the original source will get the merged code automatically of course.
5. Once the PR is dealt with by upstream, close it on here with a comment about what happened upstream. e.g. "merged upstream as <commit-id>" or "rejected upstream".

*One special case: perhaps the automatic PR email from the script can include a reply address that will add comments sent over email to the pull request comment section? I know you can respond to GitHub PRs via email when you get sent email notification. In any case, this is only one-way: The maintainer can reply to GitHub but the submitter can't post a GitHub comment and expect it to appear on the mailing list (unless there's even more GitHub action magic available for that?)

As you can see, it involves a bit of manual labour and/or a fair bit of GitHub-side automation work (if that's possible). I really just think anyone who can reasonably be expected to learn git email workflow should bite the bullet; I didn't find it that hard myself. gpcf has a good link for a git email workflow tutorial website but I can't find it with a search engine right now.

As an alternative let me list the steps for dealing with sourcehut directly:

0.  (once only) `git config --global --edit`. Fill out the following fields, e.g. for Outlook - other email providers will also provide their SMTP info, usually with a quick internet search. You may have already used this kind of info to set up email accounts in your email client.
```
# The user section will probably already be present if you've already committed before.
# This info is automatically filled into the email when you start to send.
[user]
    email = address@outlook.com
    name = Ty Coon
[sendemail]
    smtpencryption = tls
    smtpserver = smtp-mail.outlook.com
    smtpuser = address@outlook.com
    smtpserverport = 587
```
1.  Mark your commit with a branch. Check out the branch.
2. `git send-email master..HEAD`
3. To: [~gpcf/misc-patches@lists.sr.ht]() or other mailing address list
3. Choose the edit option and add a message there much like writing a PR message. Add the message above the first `---`
4. Save the file and send the message - you will need to enter your password each time you send the email.
5. Repeat 3-4 for each commit interactively. Yes, one email per commit.
6. Respond to any emails you receive with Reply-All in any email client of your choosing.

That's not that difficult in my opinion. I get it though  - you just want to be able to navigate to GitHub.com and see your notifications, and you want making PRs to be as simple as pushing a GUI button and typing some text in your browser. I just think that unless we're talking about somebody who has no idea how to use a command line, following the steps I provided is easier because it avoids double handling by doing the maintainer's way.

**Comment by S-S-X** [comment]
Sounds good but can be way simpler.

I think following workflow would work for us:
* Create fork repo to mt-mods org (and possibly delete mirror repo from minetest-mirrors).
* Add workflow to create pull requests from upstream repo to mt-mods repo.
* Create workflow that sends patch to ~gpcf/misc-patches@lists.sr.ht when mt-mods pull request is merged.

Good:
* Fairly simple and similar workflow is already in use for some repos (excluding post merge patch mailing)
* Allows having some different content/commits on mt-mods repo
    * still allows upstream to accept patches
    * still allows pulling updates from upstream
* Large parts of this workflow is already in use and proven to be usable.

Bad:
* Workflow will fail if upstream wont accept or reject patch as is but overwrites patch contents without adding their own commits
    * In that case it might be better to forget about upstream and only pull one way from upstream, I would not recommend doing extra work just to post patches toward upstream in that case.

Opinion based:
* Restricts merge strategy on mt-mods side to keep manageable history

**Comment by S-S-X** [comment]
Apologies for ambiguous "workflow"-use, corrections to make it clear:
* Add _automated github workflow actions_ to create pull requests from upstream repo to mt-mods repo.
* Create _automated github workflow actions_ that sends patch to ~gpcf/misc-patches@lists.sr.ht when mt-mods pull request is merged.

**Comment by y5nw** [comment]
> Create workflow that sends patch to ~gpcf/misc-patches@lists.sr.ht when mt-mods pull request is merged.

This does need some consideration as it would basically mean that the mailing list (i.e. upstream) is not notified about the pull request. I would prefer a system where Github and the sourcehut list are effectively bridged, somewhat similar to what Montandalar mentioned. The rest looks good.

Also, @gpcf: how did you set up the advtrains repo so that git.bananach.space automatically pushes to sourcehut? is that possible with Github?

**Comment by S-S-X** [comment]
> This does need some consideration as it would basically mean that the mailing list (i.e. upstream) is not notified about the pull request.

Yes it would be just another fork where things are reviewed on other side and changes offered to upstream and some attempts made to allow having similar history on both sides without large discrepancies.
Good thing is that it allows having somewhat diverging histories through separate merge commits and basically would mean that there's no need to wait for upstream to accept merge requests. (and that workflow is already actively used for other repos where upstream is hosted similar way)

Notifications could still be added but it is a lot more work with github workflow actions, have not seen that anywhere yet but it should be possible.

**Comment by Montandalar** [comment]
Spoke to Och_Nö on LinuxForks server today. He said that anyone who plays on that server should contact him there in-game, otherwise the email in the commit log is the correct place to send to. Also spoke to gpcf and he said he's open to the idea of making more sourcehut mailing lists, which I think would be great for the approach I previously outlined.

I agree with S-S-X that keeping the two histories related is not strictly necessary, although of course it may be cleaner to do so. Most linuxforks mods don't get commits very often anyway so it may hardly matter. There's the caveat though that using the patch method doesn't preserve commit ids, whereas direct pulling does.

**Comment by SwissalpS** [comment]
closing in favour of #4

**Pull request closed without merging**
